### ISSUE TITLE
1.6 stopped working with other api urls :(

### ISSUE THREAD

**Issue by Spectralo** [wakatime/zed-wakatime#10]
I really don't know what I can give you to troobleshoot but its not working anymore on https://waka.hackclub.com/ :(
Im using wakatime.cfg file in my home directory.

**Comment by alanhamlett** [comment]
We only support official WakaTime API not third parties.

**Comment by Baraban511** [comment]
Sad :cry: . Any plan for a future version ? I would be interested too
