### ISSUE TITLE
Language server error

### ISSUE THREAD

**Issue by VerifiedFemboy** [wakatime/zed-wakatime#6]
So I think it started after update it worked before and right now is not working
![image](https://github.com/user-attachments/assets/ccbdad4b-82f6-47a2-89b4-279a4a3039fe)

I am on Linux so I don't know is this only issue on Linux

**Comment by VerifiedFemboy** [comment]
and of course I tried to set api key on zed settings and also wakatime config, both are no working

**Comment by bestgopher** [comment]
Hi. Could you check the language server debug logs? 
![image](https://github.com/user-attachments/assets/9e50f3b0-9962-40fb-8bf6-cb5390d849af)
![image](https://github.com/user-attachments/assets/11d52c8e-3d19-4ba9-974d-7cca12dcecac)
![image](https://github.com/user-attachments/assets/32b123bd-0815-4d98-afef-42c8b65b08c3)

**Comment by kaf-lamed-beyt** [comment]
The error i'm getting is 👇🏼 

```shell
Language server error: wakatime

status error 403, response: "{\"message\":\"API rate limit exceeded for 104.28.154.185. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
-- stderr--
```

PS: I already included my API key

**Comment by bestgopher** [comment]
> The error i'm getting is 👇🏼
> 
> ```shell
> Language server error: wakatime
> 
> status error 403, response: "{\"message\":\"API rate limit exceeded for 104.28.154.185. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n"
> -- stderr--
> ```
> 
> PS: I already included my API key

Are you sure that WakaTime has been installed successfully?

**Comment by kaf-lamed-beyt** [comment]
Ah yes. I even had to uninstall and install it again.

**Comment by bestgopher** [comment]
> Ah yes. I even had to uninstall and install it again.

You have been banned by GitHub.

**Comment by VerifiedFemboy** [comment]
Okay I forgot to respond with logs and I will send them today in the evening because I am not home right now

**Comment by kaf-lamed-beyt** [comment]
> > Ah yes. I even had to uninstall and install it again.
> 
> You have been banned by GitHub.

Banned by GitHub? any idea why that happens?

**Comment by VerifiedFemboy** [comment]
Okay I reinstalled and it is working

**Comment by bestgopher** [comment]
@kaf-lamed-beyt If you have no further questions, I will close the issue.

**Comment by kaf-lamed-beyt** [comment]
what exactly do you think i can do about the issue &mdash; being "banned by GitHub" @bestgopher? 

because, I've tried to install and uninstall the extension, plus I used a new API key too

**Comment by bestgopher** [comment]
@kaf-lamed-beyt Are you still unable to install it successfully and encountering the same issue?

**Comment by bestgopher** [comment]
> Hi. Could you check the language server debug logs? ![image](https://private-user-images.githubusercontent.com/36840497/382622458-9e50f3b0-9962-40fb-8bf6-cb5390d849af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI0NTgtOWU1MGYzYjAtOTk2Mi00MGZiLThiZjYtY2I1MzkwZDg0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjBjM2U5Y2QxZjBjNjVmMTBkZTM1ODM3NjA4NDEwMjI3MDFjNWRmNWQ4NWNmMzI0ZTY0ZjczODZhZWI5YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.obMfvO9rD9UcmUyol5j5pRRxvB7cIH4ta5zPZS6oTB8) ![image](https://private-user-images.githubusercontent.com/36840497/382622484-11d52c8e-3d19-4ba9-974d-7cca12dcecac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI0ODQtMTFkNTJjOGUtM2QxOS00YmE5LTk3NGQtN2NjYTEyZGNlY2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmM2Q1NDNlNzM5YjhjNjE2NGI5YzE3NzYzZGUwNWFhNDM4ODMzZDg4NGQ4ZDc2MDY2ZWQ2MjM0NDg2NzdlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tqVwI4VGK396UmRYxQQSt1H7CG4VJVQEWkSLwyBKKR0) ![image](https://private-user-images.githubusercontent.com/36840497/382622535-32b123bd-0815-4d98-afef-42c8b65b08c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI1MzUtMzJiMTIzYmQtMDgxNS00ZDk4LWFmZWYtNDJjOGI2NWIwOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOWI0ZTRhMTljNzc5NGFiZDJlNjU0YTA5MDQ3Mzk5YzViZDBkYTQwMTcyMTkzY2Y5MjhmNDI3N2I2NDY2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tjcC4-0ckwGIXBc6gcXafOuoulzcKH1w6kJ2qbulUcA)

@kaf-lamed-beyt Could you try it.

**Comment by kaf-lamed-beyt** [comment]
> @kaf-lamed-beyt Are you still unable to install it successfully and encountering the same issue?
> 

I am able to Uninstall it. But, it just doesn't track my time.

**Comment by kaf-lamed-beyt** [comment]
> > Hi. Could you check the language server debug logs? ![image](https://private-user-images.githubusercontent.com/36840497/382622458-9e50f3b0-9962-40fb-8bf6-cb5390d849af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI0NTgtOWU1MGYzYjAtOTk2Mi00MGZiLThiZjYtY2I1MzkwZDg0OWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjBjM2U5Y2QxZjBjNjVmMTBkZTM1ODM3NjA4NDEwMjI3MDFjNWRmNWQ4NWNmMzI0ZTY0ZjczODZhZWI5YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.obMfvO9rD9UcmUyol5j5pRRxvB7cIH4ta5zPZS6oTB8) ![image](https://private-user-images.githubusercontent.com/36840497/382622484-11d52c8e-3d19-4ba9-974d-7cca12dcecac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI0ODQtMTFkNTJjOGUtM2QxOS00YmE5LTk3NGQtN2NjYTEyZGNlY2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmM2Q1NDNlNzM5YjhjNjE2NGI5YzE3NzYzZGUwNWFhNDM4ODMzZDg4NGQ4ZDc2MDY2ZWQ2MjM0NDg2NzdlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tqVwI4VGK396UmRYxQQSt1H7CG4VJVQEWkSLwyBKKR0) ![image](https://private-user-images.githubusercontent.com/36840497/382622535-32b123bd-0815-4d98-afef-42c8b65b08c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDc3MDUsIm5iZiI6MTczMTMwNzQwNSwicGF0aCI6Ii8zNjg0MDQ5Ny8zODI2MjI1MzUtMzJiMTIzYmQtMDgxNS00ZDk4LWFmZWYtNDJjOGI2NWIwOGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2NDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlOWI0ZTRhMTljNzc5NGFiZDJlNjU0YTA5MDQ3Mzk5YzViZDBkYTQwMTcyMTkzY2Y5MjhmNDI3N2I2NDY2ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tjcC4-0ckwGIXBc6gcXafOuoulzcKH1w6kJ2qbulUcA)
> 
> @kaf-lamed-beyt Could you try it.

okay. lemme do this.

**Comment by kaf-lamed-beyt** [comment]
This is what I'm seeing all through

```shell
[GLOBAL] No matching project for document {
  fsPath: 'path/to/project/src/containers/catalogues/index.tsx',
  normalPath: path/to/project/src/catalogues/index.tsx'
}
```

**Comment by kaf-lamed-beyt** [comment]
I don't get you... want me to send the entire log?

**Comment by bestgopher** [comment]
First, we should make sure that the extension is installed successfully. Then, check the language server log to ensure that wakatime-cli executed successfully.

**Comment by kaf-lamed-beyt** [comment]
I don't think the language server is active though

This is what I can see in the debug log 
![Screenshot from 2024-11-11 09-20-23](https://github.com/user-attachments/assets/e225bb24-fa5f-460c-bd4b-d8521b08b213)

And I have the extension installed. 

![image](https://github.com/user-attachments/assets/1d01d7fd-defe-4b2a-b627-8ca24a35d08c)

This is what my settings JSON looks like 

![image](https://github.com/user-attachments/assets/7b28d994-2c67-42b5-875d-154cd3c2ddb9)

**Comment by kaf-lamed-beyt** [comment]
Here @bestgopher 

```shell
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320751\" \"--write\" \"false\" \"--entity\" \"/home/seven/codes/jobs/livenormad/live-normad/src/containers/wall-quotation/components/estimation/index.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--guess-language\" \"--lineno\" \"75\" \"--cursorpos\" \"16\"","type":4}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320754\" \"--write\" \"false\" \"--entity\" \"/home/seven/Documents/codes/jobs/livenormad/live-normad/src/components/center-spinner.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--language\" \"tsx\"","type":4}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320756\" \"--write\" \"false\" \"--entity\" \"/home/seven/Documents/codes/jobs/livenormad/live-normad/src/containers/wall-quotation/components/estimation/index.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--guess-language\" \"--lineno\" \"75\" \"--cursorpos\" \"16\"","type":4}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320758\" \"--write\" \"false\" \"--entity\" \"/home/seven/Documents/codes/jobs/livenormad/live-normad/src/containers/wall-quotation/components/estimation/index.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--guess-language\" \"--lineno\" \"75\" \"--cursorpos\" \"16\"","type":4}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320760\" \"--write\" \"false\" \"--entity\" \"/home/seven/Documents/codes/jobs/livenormad/live-normad/src/containers/wall-quotation/components/estimation/index.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--guess-language\" \"--lineno\" \"75\" \"--cursorpos\" \"15\"","type":4}}
// Receive:
{"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Wakatime  command: \"/home/seven/.local/share/zed/extensions/work/wakatime/wakatime-cli-v1.104.0/wakatime-cli-linux-amd64\" \"--time\" \"1731320762\" \"--write\" \"false\" \"--entity\" \"/home/seven/Documents/codes/jobs/livenormad/live-normad/src/containers/wall-quotation/components/estimation/index.tsx\" \"--plugin\" \"Zed/0.160.7 Zed-wakatime/0.1.5\" \"--guess-language\" \"--lineno\" \"75\" \"--cursorpos\" \"15\"","type":4}}

```

**Comment by bestgopher** [comment]
@kaf-lamed-beyt Hi, could you reinstall it? I have rebuilt it.

**Comment by kaf-lamed-beyt** [comment]
Alright. I'll do that now

**Comment by kaf-lamed-beyt** [comment]
Still doesn't track my time, @bestgopher

**Comment by bestgopher** [comment]
Did you try using wakatime-cli directly, and does it work?

**Comment by kaf-lamed-beyt** [comment]
nahh... haven't tried using it. 

I'm on Ubuntu OS. Could it be the reason why the extension doesn't work for me?

**Comment by bestgopher** [comment]
Hi, I’m not sure why it’s not working. Could you provide more log information, such as the Zed log and LSP debug log?

**Comment by kaf-lamed-beyt** [comment]
It just suddenly starts to work now. @bestgopher. 

I don't know why. But, I think it is because I went and updated my Wakatime API key in VSCode and restarted Zed. I know this doesn't make sense. But, that's all I can thnk of.
