### ISSUE TITLE
Why is the Editor name "Preview" instead of Zed?

### ISSUE THREAD

**Issue by kaido2ki** [wakatime/zed-wakatime#8]
OS: ArchLinux

![image](https://github.com/user-attachments/assets/b3eb5ee4-0f39-42e3-baa7-9ad356d9b29e)

**Comment by bestgopher** [comment]
Hi, please check the LSP log to ensure that the plugin's name is correct.

![image](https://github.com/user-attachments/assets/d5fba3a6-1b9b-4d4a-bb47-0fa25c650368)

**Comment by bestgopher** [comment]
1. ctrl-shift-p 
<img width="448" alt="image" src="https://github.com/user-attachments/assets/77710618-b22a-42e7-99d9-25bbee222978">

2.
<img width="462" alt="image" src="https://github.com/user-attachments/assets/af878685-025e-481b-b11f-63efc2c3d875">

3.
<img width="243" alt="image" src="https://github.com/user-attachments/assets/db54b24f-1c20-4338-81cb-488e4e1de063">

4.
<img width="358" alt="image" src="https://github.com/user-attachments/assets/1b17bc72-b198-4435-8251-484238b0a870">

**Comment by bestgopher** [comment]
I will fix it later.

**Comment by gandarez** [comment]
@alanhamlett I think it can be fixed on the server side since the plugin is `Zed Preview` and not `Zed`?
